improved/fixed workflow

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -24,8 +24,13 @@ jobs:
       - name: Provision customer
         run: |
           customer_id=$(./bin/setup.sh "${{ secrets.PARTNER_ID }}" "${{ secrets.PARTNER_SECRET }}" "${{ secrets.APP_KEY }}" --no-interaction | grep -oP '(?<=CUSTOMER_ID: )\d+')
-          echo "CUSTOMER_ID=$customer_id" >> "$GITHUB_ENV"
+          if [ -z "$customer_id" ]; then
+            echo "Failed to provision customer_id"
+            exit 1
+          fi
+          echo "CUSTOMER_ID=$customer_id" >> "$GITHUB_ENV
       - name: Run Tests
+        timeout-minutes: 30
         run: |
           cd tests
           mvn clean test -DpartnerId=${{ secrets.PARTNER_ID }} -DpartnerSecret=${{ secrets.PARTNER_SECRET }} -DappKey=${{ secrets.APP_KEY }} -DcustomerId="${{env.CUSTOMER_ID}}"
